# Generated by Django 4.0.2 on 2022-02-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
