# Generated by Django 4.0.2 on 2022-02-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dg', '0002_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
    ]
